name: store
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  #language
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #Firebase
  firebase_core: ^3.5.0
  #Core
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^6.0.5
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.1
  very_good_analysis: ^6.0.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/core/
    - assets/images/admin/
    - assets/images/customer/
    - assets/images/svg/
    - assets/images/appicon.jpeg
    - .env.dev
    - .env.prod
    - lang/ar.json
    - lang/en.json


  fonts:
    #Arabic Font
    - family: Cairo
      fonts:
        - asset: assets\fonts\arabic\cairo\Cairo-Bold.ttf
          weight: 700
        - asset: assets\fonts\arabic\cairo\Cairo-Medium.ttf
          weight: 500
        - asset: assets\fonts\arabic\cairo\Cairo-Regular.ttf
          weight: 400
    #English Font      
    - family: Poppins
      fonts:
        - asset: assets\fonts\english\poppins\Poppins-Bold.ttf
          weight: 700
        - asset: assets\fonts\english\poppins\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\english\poppins\Poppins-Regular.ttf
          weight: 400
